# -*- mode: ruby -*-
# vi: set ft=ruby :
# noinspection RubyResolve

# WINDOWS MUST-DO: vagrant up MUST be be run in an elevated cmd prompt
# to get SeCreateSymbolicLinkPrivilege for symlinks used by npm install
# (or update npm version and use --no-bin-links)

Vagrant.configure("2") do |config|
  # The official ubuntu 16.4 cloud" images are broken: https://bugs.launchpad.net/cloud-images/+bug/1627931
  # Using bento/ubuntu to get vagrant friendly login behavior - https://atlas.hashicorp.com/bento
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.network "forwarded_port", guest: 443, host: 443
  config.vm.synced_folder "../", "/workspace",
                          mount_options: ["dmode=777,fmode=777"]
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
     vb.cpus = "2"
     vb.name = "aws-audits-localdev"
  end

  config.vm.provision "shell", path: "scripts/install_runtime_dependencies.sh",
                      env: {:APP_APT_UPGRADE => 'True'}

  config.vm.provision "shell", path: "scripts/install_dev_dependencies.sh"

  # COMMENT OUT BELOW if you wish to create basic VM to export as an appliance.ova
  # to be used with $ packer build -only local -var-file variables/local.json build.json

  # Use either of the below sections
  config.vm.provision :shell, :path => "scripts/install_vagrant_localdev.sh",
                      env: {
                          :APP_AWS_API_ACCESS_KEY => ENV['AWS_ACCESS_KEY_ID'],
                          :APP_AWS_API_SECRET_KEY => ENV['AWS_SECRET_ACCESS_KEY'],
                          :APP_FRONTEND_BASE_PATH => '/workspace/frontend',
                          :APP_BACKEND_BASE_PATH => '/workspace/backend',
                          :APP_DEBUG => 'True',
                          :APP_DB_URI => 'mysql://awsaudits:changeme@localhost:3306/awsaudits',
                          :APP_USE_KMS => 'False',
                          :APP_USER_DATA_URL => 'http://169.254.169.254/latest/user-data'
                      }

  # config.vm.provision :shell, :path => "scripts/install_vagrant_standalone.sh",
  #                     env: {
  #                           :APP_TEMP_BASE => '/tmp/silly',
  #                           :APP_FRONTEND_BASE_PATH => '/opt/aws-audits-frontend',
  #                           :APP_BACKEND_BASE_PATH => '/opt/aws-audits-backend',
  #                           :APP_AWS_API_ACCESS_KEY => ENV['AWS_ACCESS_KEY_ID'],
  #                           :APP_AWS_API_SECRET_KEY => ENV['AWS_SECRET_ACCESS_KEY'],
  #                           :APP_APT_UPGRADE => 'True',
  #                           :APP_DEBUG => 'True',
  #                           :APP_DB_URI => 'mysql://awsaudits:changeme@localhost:3306/awsaudits',
  #                           :APP_SSL_ENABLED => 'True',
  #                           :APP_SSL_CERT_DATA => '',
  #                           :APP_SSL_KEY_DATA => '',
  #                           :APP_USE_KMS => 'False',
  #                           :APP_USER_DATA_URL => 'http://169.254.169.254/latest/user-data'
  #                     }


end
