"""resource mapping table for parent/children

Revision ID: 5895a966744d
Revises: 873cb6d2a7ed
Create Date: 2017-10-19 15:21:12.294415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = '5895a966744d'
down_revision = '873cb6d2a7ed'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_mappings',
        sa.Column('id', mysql.INTEGER(), nullable=False),
        sa.Column('parent', sa.String(length=256), nullable=False),
        sa.Column('child', sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_mappings_child'), 'resource_mappings', ['child'], unique=False)
    op.create_index(op.f('ix_resource_mappings_parent'), 'resource_mappings', ['parent'], unique=False)
    op.execute('ALTER TABLE resource_mappings PARTITION BY KEY(`id`) PARTITIONS 10')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_mappings')
    # ### end Alembic commands ###
