"""Adding some more indexes

Revision ID: 5ea7147fe9e5
Revises: c717038386e7
Create Date: 2017-11-07 14:46:09.387383

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '5ea7147fe9e5'
down_revision = 'c717038386e7'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_issue_properties_issue_id'), 'issue_properties', ['issue_id'], unique=False)
    op.create_index(op.f('ix_resource_properties_resource_id'), 'resource_properties', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_types_resource_type'), 'resource_types', ['resource_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_types_resource_type'), table_name='resource_types')
    op.drop_index(op.f('ix_resource_properties_resource_id'), table_name='resource_properties')
    op.drop_index(op.f('ix_issue_properties_issue_id'), table_name='issue_properties')
    # ### end Alembic commands ###
