"""Adding account_type to account objects

Revision ID: 873cb6d2a7ed
Revises: d88abbf9af59
Create Date: 2017-10-13 12:45:53.569363

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '873cb6d2a7ed'
down_revision = 'd88abbf9af59'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_type', sa.String(length=50), server_default='AWS', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'account_type')
    # ### end Alembic commands ###
