"""Adding DB indexes

Revision ID: c717038386e7
Revises: 5895a966744d
Create Date: 2017-11-02 15:04:12.839671

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = 'c717038386e7'
down_revision = '5895a966744d'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_auditlog_actor'), 'auditlog', ['actor'], unique=False)
    op.create_index(op.f('ix_config_items_key'), 'config_items', ['key'], unique=False)
    op.create_index(op.f('ix_emails_subsystem'), 'emails', ['subsystem'], unique=False)
    op.create_index(op.f('ix_emails_timestamp'), 'emails', ['timestamp'], unique=False)
    op.create_index(op.f('ix_emails_uuid'), 'emails', ['uuid'], unique=False)
    op.create_index(op.f('ix_issue_properties_name'), 'issue_properties', ['name'], unique=False)
    op.create_index(op.f('ix_issue_types_issue_type'), 'issue_types', ['issue_type'], unique=False)
    op.create_index(op.f('ix_logs_level'), 'logs', ['level'], unique=False)
    op.create_index(op.f('ix_logs_levelno'), 'logs', ['levelno'], unique=False)
    op.create_index(op.f('ix_logs_timestamp'), 'logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_resource_properties_name'), 'resource_properties', ['name'], unique=False)
    op.create_index(op.f('ix_scheduler_batches_status'), 'scheduler_batches', ['status'], unique=False)
    op.create_index(op.f('ix_scheduler_jobs_status'), 'scheduler_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_tags_value'), 'tags', ['value'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_tags_value'), table_name='tags')
    op.drop_index(op.f('ix_scheduler_jobs_status'), table_name='scheduler_jobs')
    op.drop_index(op.f('ix_scheduler_batches_status'), table_name='scheduler_batches')
    op.drop_index(op.f('ix_resource_properties_name'), table_name='resource_properties')
    op.drop_index(op.f('ix_logs_timestamp'), table_name='logs')
    op.drop_index(op.f('ix_logs_levelno'), table_name='logs')
    op.drop_index(op.f('ix_logs_level'), table_name='logs')
    op.drop_index(op.f('ix_issue_types_issue_type'), table_name='issue_types')
    op.drop_index(op.f('ix_issue_properties_name'), table_name='issue_properties')
    op.drop_index(op.f('ix_emails_uuid'), table_name='emails')
    op.drop_index(op.f('ix_emails_timestamp'), table_name='emails')
    op.drop_index(op.f('ix_emails_subsystem'), table_name='emails')
    op.drop_index(op.f('ix_config_items_key'), table_name='config_items')
    op.drop_index(op.f('ix_auditlog_actor'), table_name='auditlog')
    # ### end Alembic commands ###
