"""Create scheduler objects

Revision ID: d88abbf9af59
Revises: c09be96d7f50
Create Date: 2017-08-28 17:46:38.093512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = 'd88abbf9af59'
down_revision = 'c09be96d7f50'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_batches',
        sa.Column('batch_id', sa.String(length=36), nullable=False),
        sa.Column('status', mysql.TINYINT(), nullable=False),
        sa.Column('started', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('completed', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('scheduler_jobs',
        sa.Column('job_id', sa.String(length=36), nullable=False),
        sa.Column('batch_id', sa.String(length=36), nullable=False),
        sa.Column('status', mysql.TINYINT(), nullable=False),
        sa.Column('data', mysql.JSON(), nullable=False),
        sa.ForeignKeyConstraint(['batch_id'], ['scheduler_batches.batch_id'], name='fk_scheduler_job_batch_id', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduler_jobs')
    op.drop_table('scheduler_batches')
    # ### end Alembic commands ###
